# Generated by Django 4.1.7 on 2023-03-14 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_details', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='cost_for_two',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=5),
        ),
    ]
